task: detection

num_classes: 221
    
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: /home/kc/cl/MTSD/mtsd_fully_annotated_train_images/images
    ann_file: /mnt/thanhpd/mtsd_task0_hier/mtsd_cl/CL_rtdetr/train_output_file_coco.json
    transforms:
      type: Compose
      ops: ~

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: /home/kc/cl/MTSD/mtsd_fully_annotated_val_images/images
    ann_file: /mnt/thanhpd/mtsd_task0_hier/mtsd_cl/CL_rtdetr/val_output_file_coco.json
    transforms:
      type: Compose
      ops: ~
