task: detection

num_classes: 221
    
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: /mnt/thanhpd/MTSD/mtsd_fully_annotated_train_images/images
    ann_file: /CL_rtdetr/train_output_file_coco.json
    transforms:
      type: Compose
      ops: ~

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: /mnt/thanhpd/MTSD/mtsd_v2_fully_annotated_images.val.zip/images
    ann_file: /CL_rtdetr/val_output_file_coco.json
    transforms:
      type: Compose
      ops: ~
