
# CL General
start_task: 0
total_tasks: 2

# CL Strategy
pseudo_label: False
distill_attn: False
teacher_path: "/kaggle/input/checkpoint-for-mtsd-model/ckp_mtsd_cl_task0_schema_2.pth"

# CL Rehearsal
rehearsal: False

# CL Eval
fpp: False

# WandB
#wandb_name: "7010_t0_10e"
